# This is a basic workflow to help you get started with Actions
name: Repo-Creation

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  # Need `pull-requests: write` to create a pull request
  contents: write
  pull-requests: write
  actions: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "**" ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Setup_Project"
  Setup_Project:

    # We will only run this action when:
    # This repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template }}
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Project Name and Path Variables
        shell: pwsh
        run: |
          $Repo = $env:GITHUB_REPOSITORY # warrenbuckley/my-awesome-idea
          $Repo = $Repo.Split("/")[1] # my-awesome-idea

          $ProjectName = $Repo.Replace(" ", ".")
          $ProjectNameLower = $ProjectName.ToLower()
          $WebsiteProjectName = $ProjectName + '.Website'
          $WebsiteProjectCSProj = $WebsiteProjectName + '.csproj'
          $RCLProjectName = $ProjectName
          $RCLProjectCSProj = $RCLProjectName + '.csproj'
          $ClientProjectName = $ProjectName + '.Client'

          "project_name=$ProjectName" | Out-File -FilePath $env:GITHUB_ENV -Append
          "project_name_lower=$ProjectNameLower" | Out-File -FilePath $env:GITHUB_ENV -Append
          "website_project_name=$WebsiteProjectName" | Out-File -FilePath $env:GITHUB_ENV -Append
          "website_project_csproj=$WebsiteProjectCSProj" | Out-File -FilePath $env:GITHUB_ENV -Append
          "rcl_project_name=$RCLProjectName" | Out-File -FilePath $env:GITHUB_ENV -Append
          "rcl_project_csproj=$RCLProjectCSProj" | Out-File -FilePath $env:GITHUB_ENV -Append
          "client_project_name=$ClientProjectName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Verify Variables
        shell: pwsh
        run: |
          Write-Output "project_name: $env:project_name"
          Write-Output "project_name_lower: $env:project_name_lower"
          Write-Output "website_project_name: $env:website_project_name"
          Write-Output "website_project_csproj: $env:website_project_csproj"
          Write-Output "rcl_project_name: $env:rcl_project_name"
          Write-Output "rcl_project_csproj: $env:rcl_project_csproj"
          Write-Output "client_project_name: $env:client_project_name"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
        
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

       # Runs a single command using the runners shell
      - name: See all env variables with set
        run: set

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project !!
    
      - name: List workflows
        run: gh workflow list --all
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable workflows
        run: gh workflow disable Repo-Creation
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
